Added Dataset for KMeans
geekquad/AlgoBook pull request #248
Opened 2020-10-07 14:00 UTC by kritikaparmar-programmer

I've added Mall Customers dataset for KMeans in Kmeans folder.

2020-10-07 14:01 UTC, kritikaparmar-programmer commented
Hey @geekquad Kindly take a look at this pr.

2020-10-07 15:39 UTC, geekquad requested changes
Please add it to the [Dataset](https://github.com/geekquad/AlgoBook/tree/master/Dataset) folder as well. Thankyou :)

2020-10-07 16:07 UTC, kritikaparmar-programmer commented
@geekquad Done!

2020-10-08 13:03 UTC, geekquad approved these changes

2020-10-08 13:03 UTC, merged