Added a DP problem and Autoencoder along with dataset
geekquad/AlgoBook pull request #278
Opened 2020-10-10 03:54 UTC by anandmohan4143

Image Denoising using Autoencoder along with car image dataset and Knapsack problem using Dynamic Programming.

2020-10-11 10:45 UTC, geekquad requested changes
Amazing work @anandmohan4143. 
Please add a requirements.txt file as well.
I see that you are using a pre-trained model as well. Please make a README.md file as well, describing the Superresolution part and add the necessary details and references (if any) as well. 
For any queries feel free to reach out to me on our Slack channel. Thankyou :)

2020-10-12 05:03 UTC, anandmohan4143 reviewed
Made changes as per the request. Please have a look into it. Thank you.

2020-10-13 06:56 UTC, geekquad approved these changes

2020-10-13 06:56 UTC, geekquad approved these changes

2020-10-13 06:56 UTC, merged