RNN
geekquad/AlgoBook pull request #421
Opened 2020-12-11 18:38 UTC by kritikaparmar-programmer

# Description: Added RNN

# Issue : #364

2020-12-12 12:45 UTC, kritikaparmar-programmer commented
Hey, @geekquad Kindly take a look at this pr.

2020-12-13 07:53 UTC, geekquad requested changes
Hey @kritikaparmar-programmer, .ipynb is for the implementation part. Please make a .py file. Please make a class for RNN. Add requirements.txt file as well.

2020-12-18 21:40 UTC, kritikaparmar-programmer commented
Hey, @geekquad I've done the changes, Kindly review them.

2020-12-19 15:30 UTC, geekquad approved these changes

2020-12-19 15:30 UTC, merged